name: geo_attendance_system
description: Major Project

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  splashscreen: any
  flutter_sparkline: any
  flutter_staggered_grid_view: any
  calendarro: ^1.0.0
  firebase_auth: any
  flutter_screenutil: ^0.4.2
  table_calendar: any
  firebase_database: any
  google_maps_flutter: ^0.5.21+8
  device_id: ^0.2.0
  location: ^2.3.5
  flutter_spinkit: ^3.1.0
  imei_plugin: any

  geofencing:
    path: geofencing

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/Logo-splash.png
    - assets/icons/navigation-drawer.png
    - assets/gif/loading-gif.gif
    - assets/gif/tick.gif
    - assets/gif/close.gif
  
  fonts:

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.otf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.otf

    - family: Sansation-Bold
      fonts:
        - asset: assets/fonts/Sansation-Bold.ttf