// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmH-ZSZ44qx1bxOon7AGo73s2nS9mYowM',
    appId: '1:872665651563:android:e9723d964a67ed082dd42e',
    messagingSenderId: '872665651563',
    projectId: 'geofencing-376617',
    databaseURL: 'https://geofencing-376617-default-rtdb.firebaseio.com',
    storageBucket: 'geofencing-376617.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ZNga5ssPJhtr165v7i34BAsaoFn338s',
    appId: '1:872665651563:ios:6455cf37d4b683012dd42e',
    messagingSenderId: '872665651563',
    projectId: 'geofencing-376617',
    databaseURL: 'https://geofencing-376617-default-rtdb.firebaseio.com',
    storageBucket: 'geofencing-376617.appspot.com',
    iosClientId: '872665651563-0o82v6g0cm4a4f3nj2896kll3d82e8gq.apps.googleusercontent.com',
    iosBundleId: 'example.com.geoAttendanceSystem',
  );
}
